dbtmetabase/__init__.py, dbtmetabase/metabase.py
Introduces optional `mb_https` argument to allow HTTP connection to Metabase as per #1.
=> Allow HTTP connection to Metabase

Makefile, dbtmetabase/metabase.py
Replace `/tables` and `/fields` API calls with one `/metadata` call for initial lookup tables.
Discussion: https://github.com/gouline/dbt-metabase/issues/4
=> Use metadata API endpoint for initial lookup tables

dbtmetabase/metabase.py
The tables can be hidden/unhidden anytime, so it's useful to have
the docs always in sync.
Also, we currently fail if any tables in dbt doesn't exist in Metabase.
So, without this change, dbtmetabase doesn't work for instances that
have hidden tables.
=> Include hidden tables in Metabase

dbtmetabase/metabase.py
If there are multiple incompatibilities between the dbt docs and
Metabase, displaying them all at once makes it much easier to fix. This
allows the user to fix all errors at once, instead of fixing one,
running `dbt-metabase`, fixing the next one, and so on.
=> Display all model compatibility errors at once

README.rst, dbtmetabase/dbt.py, dbtmetabase/metabase.py
Metabase 0.39.0 renamed `special_type` to `semantic_type`. This PR renames it accordingly:
- dbt meta field `metabase.special_type` is now deprecated, use `metabase.semantic_type` instead (will be removed)
- exporter checks API response for `special_type`/`semantic_type` and applies whichever one is present for backwards compatibility with earlier Metabase versions
=> Rename `special_type` to `semantic_type`

dbtmetabase/dbt.py
Added alias support in model parsing. Also added searching for "sources" yml blocks pushing table/column documentation to metabase (defining sources is recommended by dbt best practices and often done in tandem with creating staging models). Allows using "metabase.fk_ref" in sources or models .yml in order explicitly define a metabase relationship to a table which allows us to propagate the FK relationship properly to Metabase regardless of aliasing. metabase.fk_ref is looked for first in meta before falling back to default parser.
=> Added support for aliased models and source blocks

.github/workflows/validate.yml
No functional difference but makes more sense in branch protection rules.
=> Rename 'test' workflow and 'run' status check to 'validate'

dbtmetabase/metabase.py, setup.py
I ran into this issue after I started using [dbt-invoke](https://github.com/dashlane/dbt-invoke) which generates boilerplate YAML schema files. To make it easier to populate, it adds empty descriptions for all columns.
=> Fix 400 Errors on empty-string descriptions

dbtmetabase/__init__.py
I've started testing dbt-metabase and I ran into an issue with running `dbt-metabase export` from the command line with the `--mb_https` option.
I am running Metabase locally in a [docker container](https://www.metabase.com/docs/latest/operations-guide/running-metabase-on-docker.html) and was getting an SSL error. I found while troubleshooting that I can set mb_https to False when calling the export function from a Python script, but not from the command line.
I did some research and came up with a solution that adds an argument. I've tested it locally and I'm able to run the export from the command line.  I've never made an open-source PR before 🙈 , so please feel free to give me feedback/suggestions! I realize that adding an argument may not be optimal.
=> Add Argument --mb_http

dbtmetabase/__init__.py, dbtmetabase/metabase.py, dbtmetabase/parsers/dbt_folder.py, dbtmetabase/parsers/dbt_manifest.py, tests/test_metabase.py
Big refactor of CLI/programmatic entry point arguments, to achieve some readability and consistency.
- Arguments only belonging to dbt or Metabase are clearly prefixed with `dbt_` or `metabase_` respectively (common arguments are not prefixed)
- Prefix `mb_` becomes `metabase_` for clarity
- Optional boolean arguments should be false by default, e.g. if we mandate HTTPS to be the default (as we should because it's 2021), optional override should be `use_http`, instead of `use_https` that's true by default overridable to false
- Starting to use the new default format for header comments in VS Code, not going to replace all existing ones (too lazy, maybe in the future), but any new ones or significantly reworked ones are easier to re-create than edit, e.g. see `export()`
We're making a lot …
=> Argument naming, ordering and logic consistency

dbtmetabase/metabase.py
Since Metabase 0.40.0, API responses are encapsulated in:
```
{
"data": [ "OLD RESPONSE HERE" ],
"limit": 50,
"offset": 0,
"total": 2
}
```
This change checks if "data" key is present in the root and uses that instead. I will revisit this later, if I need to cater for pagination issues in requests.
=> Fix for new pagination envelope in Metabase 0.40.0

.github/workflows/master.yml, .github/workflows/pull_request.yml, README.rst
Separate pull request build (that could be failing often) from the master branch one that does releases and is displayed in the badge at the top of README.
=> Make GitHub Actions naming consistent

.github/workflows/master.yml, .github/workflows/pull_request.yml, Makefile, pyproject.toml, requirements-test.txt, setup.py
Automatically check formatting with https://github.com/psf/black in CI (using `make check-fmt`) and allow formatting from CLI using `make fmt` (although IDE integration is easier).
=> Add formatter to CI checks

dbtmetabase/__init__.py, dbtmetabase/utils.py
Fixes missing `_version.py` when installing using pip from git branch, instead of PyPI https://github.com/gouline/dbt-metabase/pull/38#discussion_r675640224
When running from PyPI version and the `_version.py` is generated, it will use that, otherwise it will read from metadata, which seems to be populated correctly in the above installation method.
Also adding `--version` to quickly check your version, like most command-line tools.
=> Optional version import

dbtmetabase/metabase.py, dbtmetabase/parsers/dbt_folder.py, dbtmetabase/parsers/dbt_manifest.py
Addressing `pylint` errors:
By default, Python uses the local encoding and on Windows it is not UTF-8.
=> Set explicit utf-8 encoding when opening files

.github/workflows/master.yml, .github/workflows/pull_request.yml, dbtmetabase/models/metabase.py, dbtmetabase/parsers/dbt_folder.py, dbtmetabase/parsers/dbt_manifest.py, dbtmetabase/utils.py, requirements-test.txt, tests/test_dbt_folder_reader.py, tests/test_dbt_manifest_reader.py, tests/test_metabase.py, tests/utils_mb_test_suite.py
=> Restore Python 3.6+ compatibility

dbtmetabase/parsers/dbt_folder.py, dbtmetabase/parsers/dbt_manifest.py
A PR to address Issue #63 
Adds a simple conditional and an exception catch to two parts of the parser codes which can encounter edge cases like those presented in the issue.
=> Add some resiliency to parsers processsing tests nodes

.github/workflows/master.yml, .github/workflows/pull_request.yml, Makefile, README.rst, requirements-test.txt
Fix improperly formatted heading in README.rst (#76) and add reStructuredText linter to prevent this in future.
CI run: https://github.com/gouline/dbt-metabase/runs/4345047264
FYI @patygold
=> Fix README.rst that broke the build

dbtmetabase/__init__.py
Allow imports like this for programmatic instantiation:
```python
from dbtmetabase import DbtInterface, MetabaseInterface
```
Instead of:
```python
from dbtmetabase.models.interface import DbtInterface, MetabaseInterface
```
=> Expose interfaces in models

README.rst, dbtmetabase/models/metabase.py
Rationale for this PR: I've had my fair share of issues with setting the PK/FK relationships via the dbt relationships test. My current issue is that the existing logic is a two-way street and which field in a relationship is set as PK and which as FK is basically random.
This is because the manifest's `child_map` contains relationships for both the tested field as well as the related model. This is sort-of OK because if the fields are named differently (e.g. `orders.customer_id` vs `customers.id`), the un-intended relationship is not actually set because it can't find the field. However, if following a different convention (i.e. `orders.customer_id` and `customers.customer_id`), this isn't the case anymore, and the PK and FK fields may be switched up.
Instead of trying to fix the whole …
=> Feat: Enable using dbt meta to set FK relationships

dbtmetabase/__init__.py, dbtmetabase/metabase.py
This is a fix for #97.
* The `self.exposure_parser` regex will now match (most) qualified table names.
* There are some edge cases I don't account for, like quoted names with spaces.
* The exposure extractor is now case insensitive. 
* I excluded qualified names from the CTE scrubbing code, so that exposures can correctly detect things like `with name as (select * from real_data.name)`.
* `make test` passes
* I ran my version against a fairly large (600 question) metabase instance, and confirmed that it detected the expected exposure dependencies.
=> Makes native query model extraction case-insensitive, and work on qualified table names.

dbtmetabase/__init__.py
Previously, any values passed in a config.yml file for boolean flags (metabase_use_http, metabase_sync) were ignored.
This change will override any flags that are of type click.types.BoolParamType with values provided in a config.yml file, even if specified in a command line argument.
For example, when `metabase_use_http` is set to `True` in config.yml, running `dbt-metabase models --metabase_https` will still default to using HTTP.
Resolves #99
=> Ensures that boolean option flags are overridden by config.yml when no CLI flags are provided

dbtmetabase/__init__.py, dbtmetabase/logger/logging.py, dbtmetabase/metabase.py, dbtmetabase/models/interface.py, dbtmetabase/models/metabase.py, dbtmetabase/parsers/dbt_folder.py
This tool is amazing!
I have a couple features that may be helpful.
First, adding a flag to skip all dbt sources. In [our project](https://github.com/cal-itp/data-infra/tree/main/warehouse), we ultimately use Metabase on top of BigQuery, but we don't import source datasets into Metabase. Without the flag, `dbt-metabase` throws errors as it tries to sync dbt source models.
Second, adding `metabase.display_name` as an optional field. We deal with a lot of [GTFS](https://gtfs.org/) data, so our model names naturally have GTFS as a common acronym. Currently it gets title-cased as `Gtfs` in many situations, which is annoying. So I wanted to have the ability to override the Metabase `display_name` property.
=> feat: Add flag to skip syncing sources, and allow meta-defined display names

dbtmetabase/__init__.py, dbtmetabase/metabase.py, dbtmetabase/models/interface.py, dbtmetabase/models/metabase.py, dbtmetabase/parsers/dbt_folder.py, dbtmetabase/parsers/dbt_manifest.py, tests/fixtures/sample_project/models/schema.yml, tests/test_dbt_parsers.py, tests/test_metabase.py
Piggybacking off https://github.com/gouline/dbt-metabase/pull/109/files - add the ability to use display_name for fields
https://www.metabase.com/docs/latest/api/field.html#params-12
=> Add `display_name` option for field names

dbtmetabase/__init__.py
=> Fix "TypeError: models() got an unexpected keyword argument 'metabase_session_id'" (closes #113)

dbtmetabase/parsers/dbt_manifest.py
It wasn't at all clear to me what 'dbt database' should be set to - I had guessed it was the dbt profile - so this will help people figure out what we're seeing that we don't expect.
=> Improve debug message when skipping due to wrong target database

dbtmetabase/metabase.py
=> Fix default visibility_type for models (closes #116)

dbtmetabase/parsers/dbt_manifest.py
New approach of #110. This logic now allows the self reference / circular reference. 
I made this logic based on my initial work (i.e., before refactor of @gouline). By removing the set, it's now possible to have a self reference. In addition, as some assumptions are made I added some warning logger if in future dbt manifest changes.
Resolves #74
=> feat: allow self reference

dbtmetabase/metabase.py, dbtmetabase/models/metabase.py, dbtmetabase/parsers/dbt.py, dbtmetabase/parsers/dbt_folder.py, dbtmetabase/parsers/dbt_manifest.py, tests/fixtures/sample_project/models/schema.yml, tests/test_dbt_parsers.py
Providing a null `metabase.semantic_type` explicitly writes it to the API, omitting it leaves the existing one.
Changes behaviour in #118 and #119
Resolves #131
=> feat: Allow explicit null semantic types

README.rst, dbtmetabase/__init__.py
=> docs: The correct ENV var is MB_PASSWORD (#133)

README.rst, dbtmetabase/models/metabase.py, dbtmetabase/parsers/dbt.py, dbtmetabase/parsers/dbt_folder.py, dbtmetabase/parsers/dbt_manifest.py
- Renaming explicit foreign key meta fields in #139 back to `fk_target_table` and `fk_target_field`
- Updating documentation to reflect actual behaviour
- Infer semantic type `type/FK` when target provided
- Refactor meta fields specific to models vs columns (e.g. models have no semantic types)
=> fix: Folder parser meta fields and docs

dbtmetabase/__init__.py, dbtmetabase/metabase.py, dbtmetabase/models/metabase.py, dbtmetabase/parsers/dbt.py, dbtmetabase/parsers/dbt_folder.py, dbtmetabase/parsers/dbt_manifest.py
=> fix: Consistent model selection in parsing

dbtmetabase/metabase.py, dbtmetabase/models/metabase.py
Add support for the following properties:
* metabase.has_field_values
* metabase.coercion_strategy
* metabase.number_style (becomes settings -> number_style)
=> More column settings

dbtmetabase/metabase.py, dbtmetabase/models/metabase.py
Incorrect default values were causing unnecessary API updates for all tables and fields:
- #111 caused null "display_name" updates where API defaults to same value as "name" on fields
- #112 propagated the same logic to tables
- #145 caused empty "settings" to be set to `{}` instead of null on fields
Also ignoring meta fields that don't apply to either tables or columns (e.g. caveats).
=> fix: Unnecessary updates because of display_name and settings

.github/workflows/master.yml, .github/workflows/pull_request.yml, dbtmetabase/metabase.py, dbtmetabase/models/exceptions.py, dbtmetabase/models/interface.py
- Raise error when exporting models failed in non-critical way, to be able to detect failures in CI
- Re-enable pre-sync to wait on schema changes
=> Re-enable pre-sync and raise on model export failure

dbtmetabase/parsers/dbt_manifest.py, tests/test_dbt_parsers.py
The tool appears to read all relationship tests, both outgoing (the fk_target_table is a model not currently being read), as well as incoming (the fk_target_table is the model currently being read).
If table A is the table currently being read by the tool, and it has a relationship test for a field referring to table B, then that field in table A should then have a foreign key (type/FK) pointing towards table B. Currently however it also looks the other way around to find foreign key fields in table B, pointing towards table A, but uses these to mark them as foreign key fields in table A (if the field names match between both tables).
This PR ignores those incoming relationship tests when detecting fields for foreign keys.
Fixes #157
=> fix: skip incoming relationship tests

dbtmetabase/metabase.py, dbtmetabase/models/interface.py
To access the Metabase database in my company, we need to present a certificate to prove our identity. 
To do this, we need to use the Requests argument: "cert"
So I add it in the MetabaseClient object
=> feat: Add the 'cert' argument to the Requests framework

dbtmetabase/metabase.py, tests/fixtures/exposure/baseline_test_exposures.yml
https://github.com/gouline/dbt-metabase/issues/168 Since dbt 1.3 exposure names containing other characters than letters, numbers, underscores and hyphens are deprecated
- Replaced all characters not being letters, numbers or hyphens by underscores in the exposure name
- Added the original card name as exposure label
=> fixed exposure names and added labels

dbtmetabase/__init__.py, dbtmetabase/metabase.py, requirements-test.txt
Making a consistent baseline for incoming pull requests.
=> Pin updated check deps and reformat

dbtmetabase/__init__.py, dbtmetabase/metabase.py, dbtmetabase/models/interface.py
- add new options to CLI: extra_http_headers
- it allows to provide extra headers to requests sent to Metabase instance
it allows instances to be reached when they are deployed behind security system (ex https://developers.cloudflare.com/cloudflare-one/identity/service-tokens/#connect-your-service-to-access)
example
```bash
dbt-metabase models --http_extra_headers CF-Access-Client-Id $CF_CLIENT_ID --http_extra_headers CF-Access-Client-Secret $CF_CLIENT_SECRET
```  
thanks to @elongl and @elementary-data for the initial implementation
https://github.com/elementary-data/dbt-metabase/commit/91c34651ab323653c993820222670c27df19b38f
=> feat: allow custom headers to be sent through http requests

dbtmetabase/__init__.py, dbtmetabase/metabase.py, dbtmetabase/models/interface.py
=> feat: configurable metabase api timeotus

.github/workflows/master.yml, .github/workflows/pull_request.yml, README.md, requirements-test.txt, setup.py
- Require Python 3.8 as the minimum version going forward
- Update build dependencies to newer versions supported for 3.8
- Revision of #192
=> Python 3.8 minimum

.gitignore, dbtmetabase/__init__.py, pyproject.toml
This appears to be the current standard in the Python community.
=> Bring back _version.py file

Makefile, dbtmetabase/__main__.py, dbtmetabase/metabase.py, sandbox/requirements.txt, setup.py, tests/fixtures/sample_project/models/schema.yml
- Makefile targets for running model export against Docker Compose sandbox
- Fixes uncovered from testing against sandbox
=> Model export fixes discovered in sandbox testing

Makefile, dbtmetabase/__main__.py, dbtmetabase/_format.py, dbtmetabase/metabase.py, tests/fixtures/exposure/.gitignore, tests/test_metabase.py
Multiple requested improvements to exposure extraction:
- Optional grouping by type (e.g. question/123.yml) or collection (e.g. our_analytics.yml)
- Resolves #102
- Sanitize exposure descriptions to replace `{{foo}}` with `foo`
- Resolves #148
- Sort exposures by name within each YAML file
- Resolves #165
- Add inclusion collection name filtering (in addition to existing exclusion filtering)
- Resolves #201
=> Improvements to exposure extraction

dbtmetabase/manifest.py
- Fix for a "list index out of range" error in manifest reader
- Caused by using index 1 item in the list first and checking whether it's long enough second #158
=> Fix list index out of range in manifest reader

dbtmetabase/parsers/dbt_manifest.py
- Backport #210 to 0.10 release
=> Fix list index out of range in manifest reader in 0.10

README.md, dbtmetabase/_exposures.py, dbtmetabase/_models.py, dbtmetabase/core.py, dbtmetabase/format.py, dbtmetabase/manifest.py, dbtmetabase/metabase.py
- More informative logging messages
- Consistent head comments
- Minor improvements to README
=> Cleanup docs

.github/workflows/master.yml
Only run tests in pull requests where they can be fixed.
=> Remove duplicate steps from master workflow

dbtmetabase/__main__.py
Remove reference to `typing_extensions`, excessive dependency for one usage.
=> Fix missing typing_extensions dependency

dbtmetabase/__main__.py, dbtmetabase/_models.py, dbtmetabase/format.py, dbtmetabase/manifest.py, tests/test_format.py
- Filter expects a list or tuple, but if passed a string accidentally, it should still work
- Add full identifiers to API update log statements
- Propagate common values from config YAML to each command without overwriting
=> Filter precaution, API update log statements and common configs

Makefile, dbtmetabase/__main__.py
- Fix embarrassing bug parsing comma-separated list CLI flags
- Re-introduce `--http-header` CLI flag
- Requested by @tanguyantoine in https://github.com/gouline/dbt-metabase/pull/194#discussion_r1467411118
- Add examples of both to sandbox invocation in Makefile to catch similar issues early
=> Fix CLI list flags and re-introduce --http-header flag

dbtmetabase/format.py, tests/test_format.py
**Problem**
Running `dbt-metabase exposures` produces faulty `exposures.json` if the referenced Metabase questions contain multiple variables in one query.
**To reproduce**
The problem is due to the greedy nature of the `.*` regex pattern that will catch multiple sets of double braces if they exist within the same line.
_Example query:_
```
SELECT *
FROM generate_series(  DATE_TRUNC ('day',{{start_date}}  - cast({{rolling_days}} || ' days' as interval)),  DATE_TRUNC ('day',now() - interval '1 day'), '1 day') as buckets(day);
```
**Solution**
Make the regex less greedy to match as little text as possible.
=> fix exposures crashing with referencing questions with multiple variables

dbtmetabase/_exposures.py, dbtmetabase/_models.py, dbtmetabase/manifest.py, tests/_mocks.py, tests/test_exposures.py, tests/test_manifest.py, tests/test_metabase.py, tests/test_models.py
- Separate model alias from name in manifest
- Use name for dependency parsing in exposures and convert to sets to remove duplicates
- Fixes #178
=> Fix exposures depends_on refs with aliased models

Makefile, README.md, dbtmetabase/format.py, tests/test_format.py
- Wildcard expression support in all include/exclude filters
- Based on [fnmatch](https://docs.python.org/3/library/fnmatch.html) and supports all its patterns
- Fixes #232
=> Wildcard support in filters

dbtmetabase/manifest.py, sandbox/models/schema.yml, tests/fixtures/manifest-v11.json, tests/test_manifest.py
- Support column [constraints](https://docs.getdbt.com/reference/resource-properties/constraints) of types `primary_key` and `foreign_key`
- Foreign key precedence is now (lowest to highest): relationship test, constraint, meta fields
- Fixes #230
=> Support primary key and foreign key column constraints

dbtmetabase/__main__.py, dbtmetabase/_exposures.py, dbtmetabase/metabase.py
- Fix: dbt-metabase now skips unreachable resources {card, dashboard, user} in case of **requests.exceptions.HTTPError: 404 Client Error: Not Found for url**
Closes #237
=> Skip missing cards/dashboards in exposures

dbtmetabase/__main__.py, dbtmetabase/_exposures.py, dbtmetabase/metabase.py, tests/_mocks.py, tests/fixtures/api/collection/3/items.json
- Fix type and format issues in #238
- Add test case
=> Fix PR 238 and add tests

dbtmetabase/_exposures.py, tests/fixtures/api/table.json
Relates to discussion: https://github.com/gouline/dbt-metabase/discussions/241
Some data warehouses, such as snowflake, store their object names (database, schema, table, columns) in uppercase ([ref](https://community.snowflake.com/s/article/faq-when-i-retrieve-database-schema-table-or-column-names-why-does-snowflake-display-them-in-uppercase)). 
This means that metabase questions derived from the visual editor (GUI) need to have their sources lowercased in order to match with dbt's models and nodes. We already do this for SQL native queries (refs: [1](https://github.com/gouline/dbt-metabase/blob/master/dbtmetabase/_exposures.py#L250), [2](https://github.com/gouline/dbt-metabase/blob/master/dbtmetabase/_exposures.py#L255)) so this is just a continuation of that logic.
If `table.json` …
=> Handle uppercase references from Metabase GUI derived queries

dbtmetabase/__main__.py, dbtmetabase/_exposures.py, dbtmetabase/metabase.py
This PR introduces the ability to add an `--exclude-unverified-cards` flag to the `exposures` command in order to weed out exposures from cards that were not verified through metabase.
Note: I tried but could not figure out how to implement a unit test for this.
=> Add flag to exposures for excluding all unverified collection items

dbtmetabase/_exposures.py, tests/fixtures/api/dashboard/1.json
Hello! 👋
I hope this message finds you well.
I recently encountered an issue in my environment where I wasn't able to retrieve the dashboard exposures, whereas the functionality worked seamlessly for cards. Upon investigating, I suspect that there might have been a change in the reference handling, which could be causing this discrepancy.
Here is a PR to handle the change and ensure consistent retrieval of both dashboard and card exposures!
Your feedback and review of the proposed changes would be greatly appreciated. Please feel free to reach out if you have any questions or suggestions regarding this PR ! ☀️
=> Fix Dashboard Exposures Issue

README.md, dbtmetabase/__main__.py, dbtmetabase/core.py, dbtmetabase/metabase.py, tests/_mocks.py
- Support for [API keys](https://www.metabase.com/docs/latest/people-and-groups/api-keys)
- Thanks to @cdchan for bringing it to my attention in #248! 👏 
- As session ID was implemented in #83 to overcome the absence of proper authentication for automation and API keys finally fix that issue, session ID is hereby **deprecated** and will be removed in future once the community has had time to migrate to Metabase 49 or later
=> Support for API keys and session ID deprecation

CONTRIBUTING.md
- Remove any mention of discussions in documentation
- People still raising issues for everything, so I'm disabling discussions to remove double-ups
=> Remove mentions of discussions

Makefile, dbtmetabase/metabase.py, requirements-test.txt, sandbox/docker-compose.yml, sandbox/entrypoint.py
- Fix incompatibility with [Metabase 50](https://github.com/metabase/metabase/releases/tag/v0.50.0)
- Attempting to fetch internal user raises 400 Not able to modify the internal user
- Database creation was separated from initial setup
- Pinning Metabase and dbt versions for reproducibility while testing
- Minor fixes to Makefile to enable development on Linux
=> Metabase 50 support

sandbox/Dockerfile-metabase, sandbox/docker-compose.yml
For testing custom Metabase setup or whenever experiencing issues with the standard image, e.g. https://github.com/docker/for-mac/issues/7006.
=> Custom Metabase image for sandbox

README.md, requirements-test.txt, sandbox/Dockerfile, sandbox/docker-compose.yml, sandbox/models/schema.yml, sandbox/models/staging/schema.yml, tests/_mocks.py, tests/fixtures/manifest-v12.json, tests/test_manifest.py
- Upgrade test dependencies to [dbt-postgres 1.8.1](https://github.com/dbt-labs/dbt-postgres/releases/tag/v1.8.1)
- `tests` renamed `data_tests`
- Save manifest [v12](https://schemas.getdbt.com/dbt/manifest/v12/index.html) as unit test fixture
- Add sandbox Docker dependencies to build `psycopg` from source
- Upgrade sandbox Metabase to 0.50.3
- Fix session ID warning in unit test Metabase mock
=> Update tests and sandbox for dbt 1.8

sandbox/Dockerfile.metabase, sandbox/docker-compose.yml
- Rename Dockerfile-metabase to Dockerfile.metabase per convention
- Allow custom cURL flags to pass security/certificate configs
=> Rename Dockerfile.metabase and CURL_FLAGS

dbtmetabase/_models.py
- Don't fail model sync on hidden tables (still log warning though)
- Skip column sync for tables remaining hidden or switching to hidden in the current execution
- Attempt to sync columns for tables switching from hidden with a log suggesting a retry to allow Metabase to sync the stale table on errors
- Fixes #264
=> Handle hidden tables during model sync

dbtmetabase/_models.py
Tables are hidden with any non-nil value - we hide our tables with  `technical` so would be useful to update this.
=> Skip tables that are technical not just hidden

.github/workflows/master.yml, .github/workflows/pull_request.yml, README.md
- Replace black badge with ruff (migrated in #272)
- Use ubuntu-latest for actions and Python 3.8 (latest security patch)
=> Ruff badge and action versions

dbtmetabase/_exposures.py
Hello!
I am using BigQuery with Metabase and when using custom SQL I use backtick "`" for the table name like:
```sql
select *
from `dataset.table_name`
```
And doing so the `depends_on` is empty:
```
depends_on: []
```
Here is a full exemple of what I get:
```yaml
- name: game_number_of_install
label: Game number of install
description: "### Visualization: Bar\n\nNo description provided in Metabase\n\n\
\ MONTH) as Month,\n        count(1) as nb_install\n from `game_activity_marts.game_activity__marts__games_activity`\n\
where mixpanel_ce_type = \"install_game\"\nAND company_secret = ( usersecret\
\ )\n[[ AND ( date_Filter ) ]]\n[[ AND (Item_Name) ]]\ngroup by 1, 2\n```\n\n\
type: analysis
url: https://...
maturity: medium
owner:
name: Olivier Norture
email: ....
depends_on: []
```
So I …
```
=> Allow backtick for table name

dbtmetabase/_exposures.py
See https://github.com/gouline/dbt-metabase/issues/280
=> Additional metadata to understand "usability" of a card

dbtmetabase/_exposures.py, tests/fixtures/exposure/collection/our_analytics.yml, tests/fixtures/exposure/default/exposures.yml, tests/fixtures/exposure/type/card/27.yml, tests/fixtures/exposure/type/card/28.yml, tests/fixtures/exposure/type/card/29.yml, tests/fixtures/exposure/type/card/30.yml, tests/fixtures/exposure/type/card/31.yml, tests/fixtures/exposure/type/card/33.yml
- Card `average_query_time` (in milliseconds) presented as `0:00.000` in exposure metadata
- Card `last_used_at` (ISO 8601 timestamp) presented as-is in exposure metadata
- Update exposure fixtures to reflect these
- Continues #281
- Resolves #280
=> feat: query average time and last usage metadata

.github/workflows/master.yml, Makefile, pyproject.toml
- Enforce release version on setuptools-scm in the event of some uv weirdness
- Partially pin setuptools and setuptools-scm versions
=> fix scm version for release builds

.github/workflows/master.yml
Instead of when any release is created, to allow for drafts that don't do anything yet
=> only trigger release action on released event

Makefile, dbtmetabase/_exposures.py, dbtmetabase/manifest.py, dbtmetabase/metabase.py, uv.lock
- Resolves exposure dependencies by fully-qualified names `<database>.<schema>.<table>` allowing for clashing table names in different databases and schemas (e.g. ref vs source)
- #282
=> Exposure dependency resolution by fully-qualified names

dbtmetabase/_exposures.py
- Collection slugs are URL encoded (but not names!), so this decodes them before use
- Fixes #296
=> fix: unicode exposure slugs

dbtmetabase/_exposures.py
- Strip backticks surrounding fully-qualified refs in BigQuery SQL before splitting (e.g. ``dataset.table``)
- Fixes #298
=> fix: BigQuery SQL backticks

dbtmetabase/_exposures.py
- break exposure extraction up into card types to decrease cyclomatic complexity
- store exposure fields in a pass-by-reference data class instead of merging returns
=> refactor: exposure extraction context

dbtmetabase/__init__.py, dbtmetabase/_exposures.py, dbtmetabase/_models.py, tests/conftest.py, tests/test_exposures.py, tests/test_models.py
- only internal logic extracted to decrease cyclomatic complexity, not intended to be testable separately, should have mangled names (`__` prefixed), to prevent clashing names between mixins
- private but separately testable logic should be `_` prefixed and sanely named
- not prefixed public names should be maintained and refactors count as breaking changes
=> refactor: remove testable mangled names

dbtmetabase/format.py, dbtmetabase/manifest.py
=> fix sources with null databases

README.md, dbtmetabase/_models.py, dbtmetabase/manifest.py
Does what it says on the tin... Now one may use `metabase.decimals: 3` on numeric columns.
=> Support setting decimals on numeric columns

.github/workflows/codeql-analysis.yml
https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/
=> chore: update codeql to v3

dbtmetabase/_models.py
The code already tried to do this, but it actually checked if there were any entries in the column settings attribute - including those received from the API itself.
closes #315
=> Only update the settings attribute on fields if there are setting changes

dbtmetabase/_models.py, dbtmetabase/manifest.py
- Support `metabase.settings.currency` applicable to `type/Currency` semantic type
- Resolves #317
```yaml
- name: gross_purchase_amount_processed
meta:
metabase.semantic_type: type/Currency
metabase.settings:
currency: USD
```
=> feat: support column currency

dbtmetabase/_exposures.py
- When BigQuery project ID is inferred from JSON service key, it appears as `project-id-from-credentials`
- Resolves #322
=> feat: support BigQuery `project-id-from-credentials` for model FQN
