- .github/workflows/test.yml
- Makefile
- dbtmetabase/__init__.py
- dbtmetabase/dbt.py
- dbtmetabase/metabase.py
- requirements-dev.txt
- tests/__init__.py
- tests/test_dbt.py
- tests/test_dummy.py
- tests/test_metabase.py
- Unit testing structure with some dummy tests
- Linting via Pylint
- Type checking via Mypy
- GitHub Actions to run all of the above on PRs
> Unit tests, linting and type checking with CI

- dbtmetabase/__init__.py
- dbtmetabase/metabase.py
- dbtmetabase/parsers/dbt_folder.py
- tests/test_dbt_manifest_reader.py
New take on #24 since the underlying code changed so much since #24 was open.
> DbtFolder parser: collect schema info for source tables

- .github/workflows/validate.yml
- README.rst
Metabase prefixes and target database mostly.
> Fix references to renamed CLI flags in README.md

- .github/workflows/main.yml
- .github/workflows/validate.yml
- .gitignore
- MANIFEST.in
- Makefile
- README.rst
- dbtmetabase/__init__.py
- pyproject.toml
- setup.py
Automatic release process to PyPI with dynamic versions.
Current manual releases done from my machine are not scaleable.
> Automatic releases

- dbtmetabase/metabase.py
> Metabase client fix for no schemas in BigQuery

- README.rst
- dbtmetabase/__init__.py
> Fix confusion with export CLI command

- dbtmetabase/__init__.py
- dbtmetabase/metabase.py
- dbtmetabase/models/interface.py
> Fix Docs and default value for sync timeout

- dbtmetabase/__init__.py
Fix type and lint issues in #100.
> Fix issues in #100

- dbtmetabase/metabase.py
- dbtmetabase/models/metabase.py
- dbtmetabase/parsers/dbt_manifest.py
> feat: Visibility type for models

- dbtmetabase/__init__.py
- dbtmetabase/metabase.py
- dbtmetabase/models/interface.py
> fix: Metabase session ID

- dbtmetabase/metabase.py
> fix: Set semantic type only when present

- README.rst
Additions and corrections to the readme.
> chore: Update README

- dbtmetabase/__init__.py
> Added metabase_session_id parameter for exposures

- dbtmetabase/models/metabase.py
> Fix metabase.display_name population from manifests (#129)

- dbtmetabase/__init__.py
- dbtmetabase/metabase.py
- requirements.txt
> fix: Pin requirement versions and fix default sync period

- dbtmetabase/parsers/dbt_folder.py
Tentatively support explicit foreign keys, without relationship tests:
```yaml
- name: user_id
meta:
metabase.foreign_key_to: ref('users')
metabase.foreign_key_field: id
```
Works with **folder parser only** (for now, will consider adding to manifest parser in future).
> feat: Support explicit foreign key relationships

- dbtmetabase/metabase.py
- Adding 3 retries with 0.5 backoff factor for all API calls
- Reducing timeout to 15 seconds
> feat: API retries and timeout

- README.rst
- dbtmetabase/metabase.py
- tests/fixtures/exposure/baseline_test_exposures.yml
> Exposure updated format

- .github/workflows/master.yml
- .github/workflows/pull_request.yml
- Makefile
- dbtmetabase/__init__.py
- dbtmetabase/logger/logging.py
- dbtmetabase/models/interface.py
- pyproject.toml
- requirements-test.txt
- setup.py
- tests/test_dbt_parsers.py
- tests/test_metabase.py
- tests/utils_mb_test_suite.py
Add isort to enforce imports ordering to keep the contributions consistent.
> Ordering imports

- dbtmetabase/metabase.py
> Fix include_hidden param format in Metabase x.48.x

- dbtmetabase/_models.py
> Fix missed update log

- dbtmetabase/_models.py
- tests/test_format.py
> Put back fk_target_field_id for model export

- dbtmetabase/manifest.py
Fixing cases where model columns were incorrectly assigned themselves as their foreign key.
> Fix incorrect self-referencing foreign keys

- setup.py
Reflecting that model synchronization is no longer the only feature.
> Update setup description

- dbtmetabase/_exposures.py
- tests/fixtures/api/card.json
- tests/fixtures/api/card/23.json
- tests/fixtures/api/card/24.json
- tests/fixtures/api/collection/root/items.json
- tests/fixtures/exposure/collection/our_analytics.yml
- tests/fixtures/exposure/default/exposures.yml
- Fix refactoring typo when "models" key in the output was renamed "depends" in #212
- Update fixtures with a question referencing another question that reproduced this bug
- Resolves #223
> Fix exposures crash with questions referencing questions

- README.md
> Expand readme for column constraints

- tests/fixtures/exposure/default/exposures.yml
- tests/fixtures/exposure/type/card/24.yml
- tests/fixtures/test_dump_yaml.yml
- tests/test_exposures.py
- tests/test_format.py
- Fix exposure fixtures to correspond to outputs
- Extract YAML format test into fixture
> Fix exposure and format tests

- tests/fixtures/api/collection/root/items.json
- tests/fixtures/exposure/collection/our_analytics.yml
- tests/fixtures/exposure/default/exposures.yml
- Extend test coverage to join cases
- Proposed by @alex-float-on in #242
> Add card with a join to exposure tests

- dbtmetabase/_exposures.py
- Defensively sanitize exposure dependency references
- Introduced in #228 (released in [1.1.0](https://github.com/gouline/dbt-metabase/releases/tag/v1.1.0))
- Relates to #260
> Fix exposure dependencies

- dbtmetabase/_models.py
> Skip invisible tables

- Makefile
- requirements-test.txt
- tests/__init__.py
- tests/test_exposures.py
- tests/test_format.py
- tests/test_manifest.py
- tests/test_metabase.py
- tests/test_models.py
- Improve testability within IDE (e.g. VS Code)
- Migrate from unittest to pytest
> Testability in IDE and pytest

- Makefile
- dbtmetabase/__main__.py
- dbtmetabase/_exposures.py
- tests/fixtures/exposure/default/exposures.yml
- tests/test_exposures.py
> Allow tags on exposures

- .github/workflows/pull_request.yml
- Makefile
- dbtmetabase/__main__.py
- dbtmetabase/_exposures.py
- pyproject.toml
- requirements-test.txt
- sandbox/entrypoint.py
- tests/_mocks.py
- tests/test_models.py
- Migrate to Ruff for formatting and linting
- Fix issues it found
> Migrate to Ruff

- pyproject.toml
- uv.lock
Otherwise it's appearing as an available extra in PyPI.
> Remove dev dependencies from test extra

- .github/workflows/codeql-analysis.yml
- .github/workflows/master.yml
- .github/workflows/pull_request.yml
> Update checkout and setup-python actions

- dbtmetabase/manifest.py
- Check relationship `depends_on` in group depending unique ID
- Resolves #288
> Support relationships to sources

- dbtmetabase/manifest.py
- tests/fixtures/manifest-v2.json
- tests/test_manifest.py
- #291
- Fix type issue introduced by me in suggested commits
> Meta description

- dbtmetabase/_exposures.py
- Fix crash when exposure database is mysteriously missing `details` 
- Warning log to flag unresolved exposure dependencies
- Resolves #329
> fix: exposure dependency parsing safety and logging

- .github/workflows/pull_request.yml
- .gitignore
- Makefile
- pyproject.toml
- uv.lock
Replace mypy with pyright for type checking
> chore: mypy -> pyright
